CREATE TABLE clientes (
  ClienteID INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(100) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Endereco VARCHAR(50) NOT NULL,
  Cidade VARCHAR(50) NOT NULL,
  Host VARCHAR(50),
  PRIMARY KEY (clienteID)
);

