version: "3.9"

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: db_database
      MYSQL_USER: root
      MYSQL_PASSWORD: db_password
      MYSQL_ROOT_PASSWORD: db_password
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/banco.sql
    ports:
      - "3306:3306"
    networks:
      - my-net
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.php:/usr/share/nginx/html/index.php
    ports:
      - "80:80"
      - "4500:4500"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
